spring:
  activemq:
      broker-url: failover:(tcp://101.200.161.45:61616?wireFormat.maxInactivityDuration=0)
      in-memory: true
      pool:
        enabled: true # 如果此处设置为true，需要加activemq-pool依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败